trigger: 
- relase

stages:
  - stage: build-stage
    displayName: Build Stage
    jobs:
      - job: build
        pool: 
         name: default
        steps:
          - script: "echo hellow world"
            displayName: Hello world